name: Automated API tests usign CI piplines threw Postman

on: push

env:
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Newman and Newman report
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Fetch Postman collection
        run: |
          curl -X GET "https://api.getpostman.com/collections/36297486-d72e22f1-8891-47e0-b716-27f1b27a18db" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" > collection.json
        shell: bash
      - name: Fetch Postman environment
        run: |
          curl -X GET "https://api.getpostman.com/environments/36297486-855c32fa-357e-41b5-89c0-0db6cfd525aa" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" > environment.json
        shell: bash
      - name: Run API test
        run: |
          newman run collection.json -e environment.json --reporters cli,htmlextra --reporter-htmlextra-export report.html
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html